make:
	avr-gcc -g -O3 -mmcu=atmega32u4 -c security.c
	avr-gcc -g -O3 -mmcu=atmega32u4 -c wlan.c
	avr-gcc -g -O3 -mmcu=atmega32u4 -c socket.c
	avr-gcc -g -O3 -mmcu=atmega32u4 -c hci.c
	avr-gcc -g -O3 -mmcu=atmega32u4 -c cc3000_common.c
	avr-gcc -g -O3 -mmcu=atmega32u4 -c evnt_handler.c
	avr-gcc -g -O3 -mmcu=atmega32u4 -c netapp.c
	avr-gcc -g -O3 -mmcu=atmega32u4 -c nvmem.c
	avr-gcc -g -O3 -mmcu=atmega32u4 -c spi.c
